# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LockFile::NetLock
version:      0.31
version_from: lib/LockFile/NetLock.pm
installdirs:  site
requires:
    Net::FTP                    0

distribution_type: module
generated_by: hacked manually
